#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # After downloading Xcode
  sudo xcodebuild -license # agree with license
  xcode-select --install # Install command line tool

  # install oh my zsh
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # Set node 12 as default
  nvm install 12
  nvm alias default 12

  # Set python 3.8.x as default
  pyenv install 3.8.5
  pyenv global 3.8.5

fi

